openapi: '3.0.2'
info:
  title: Wallet management
  version: '1.0'
servers:
  - url: https://wallet.com
tags:
  - name: "currency"
  - name: "account"
  - name: "transaction"
paths:
  /currency:
    get:
      tags:
        - "currency"
      summary: get All currencies
      operationId: getCurrencies
      responses:
        '200':
          description: operation successfully 
          content:
             application/json:
              schema: 
                type: array
                items:
                  $ref: "#/components/schemas/currency"

components:
  schemas:
    currency:
      type: object
      properties:
        id: 
          type: string
          format: uuid
        type:
          type: string
    account:
      type: object
      properties:
        id:
          type: integer
        idCurrency: 
          type: string
          format: uuid
    transaction:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
        transactionDate:
          type: string
          format: datetime
        amount:
          type: integer
        idAccount:
          type: integer
        