openapi: '3.0.2'
info:
  title: Wallet management
  version: '1.0'
servers:
  - url: https://wallet.com
tags:
  - name: "currency"
  - name: "account"
  - name: "transaction"
paths:
  /currency:
    get:
      tags:
        - "currency"
      summary: get All currencies
      operationId: getCurrencies
      responses:
        '200':
          description: successfully retrieved currencies
          content:
             application/json:
              schema: 
                type: array
                items:
                  $ref: "#/components/schemas/currency"
    post:
      tags:
        - "currency"
      summary: Create a currency
      operationId: createCurrency
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/currency"
      responses:
        '200':
          description: Currency created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/currency"
        '400':
          $ref: "#/components/responses/400"
        '500':
          $ref: "#/components/responses/500"
components:
  schemas:
    currency:
      type: object
      properties:
        id: 
          type: string
          format: uuid
        type:
          type: string
    account:
      type: object
      properties:
        id:
          type: integer
        idCurrency: 
          type: string
          format: uuid
    transaction:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
        transactionDate:
          type: string
          format: datetime
        amount:
          type: integer
        idAccount:
          type: integer
    Exception:
          type: object
          properties:
            type:
              type: string
            message:
              type: string
    BadRequestException:
          allOf:
            - $ref: '#/components/schemas/Exception'
          example:
            type: BadRequestException
            message: Bad request
    NotAuthorizedException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: NotAuthorizedException
        message: Not authorized
    InternalServerException:
        allOf:
          - $ref: '#/components/schemas/Exception'
        example:
          type: InternalServerException
          message: Unexpected error   
    status:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    body:
      type: object
    APIresponse:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/status"
        body:
          $ref: "#/components/schemas/body"
    Response200:
      allOf:
        - $ref: "#/components/schemas/APIresponse"
  responses:
    '200':
      $ref: "#/components/schemas/Response200"
    '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
    '403':
        description: Forbidden
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotAuthorizedException'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerException'